# 1. Secret
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: default
type: Opaque
stringData:
  accessKeyID: FciON++D7ll4ktG7M6ROERBzsgkuER5lWSXyUDMy
  secretAccessKey: FciON++D7ll4ktG7M6ROERBzsgkuER5lWSXyUDMy
---
# 2. StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: s3-storage
provisioner: s3.csi.k8s.io
parameters:
  mounter: fuse
  bucket: contabo-vps-backup
  region: eu-central-1
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
# 3. PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: s3-storage
---
# 4. Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-s3-pods-deployment
  labels:
    app: kubia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: knrt10/kubia
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: s3-pvc
