name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to K8s Cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0
    - name: Create kubeconfig file
      run: |
        mkdir -p ~/.kube
        cat <<EOF > ~/.kube/config
        apiVersion: v1
        kind: Config
        clusters:
        - name: github-k8s
          cluster:
            server: ${{ secrets.K8S_SERVER }}
            certificate-authority-data: ${{ secrets.K8S_CA }}
        contexts:
        - name: github-context
          context:
            cluster: github-k8s
            user: github-actions
        current-context: github-context
        users:
        - name: github-actions
          user:
            token: ${{ secrets.K8S_TOKEN }}
        EOF

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubia-simple-deployment.yml

    - name: Verify deployment rollout
      run: |
        kubectl rollout status deployment/kubia
